### ISSUE TITLE
Do you have a sample project for the 2019 version

### ISSUE THREAD

**Issue by luo647** [RWS/trados-studio-api-samples#25]
I want to develop a 2019 version plugin;
How do I obtain the 2019 version of the sample project？

**Comment by rwsdwatson** [comment]
Hi,
I have made a release of the code at the latest version for Trados Studio 2019.

https://github.com/RWS/trados-studio-api-samples/releases/tag/Studio2019

**Comment by luo647** [comment]
2021版本的示例项目有吗，多谢；

**Comment by rwsdwatson** [comment]
https://github.com/RWS/trados-studio-api-samples/releases/tag/Studio2021

**Comment by luo647** [comment]
> https://github.com/RWS/trados-studio-api-samples/releases/tag/Studio2021

Can I develop a plugin for 2019 version using Microsoft Visual Studio 2017?
I find the 2021 SDK at the Extention and installed it, but the project still cannot find the corresponding API.

**Comment by rwsdwatson** [comment]
have you installed the visual studio extension, I think that version supports VS2017

https://marketplace.visualstudio.com/items?itemName=sdl.project-templates-for-trados-studio-2019

**Comment by luo647** [comment]
> have you installed the visual studio extension, I think that version supports VS2017
> 
> https://marketplace.visualstudio.com/items?itemName=sdl.project-templates-for-trados-studio-2019
sorry, I made a mistake;
Actually, what I want to ask is that can I develop 2021 version using Visual Studio 2017

**Comment by rwsdwatson** [comment]
It may be possible if you install the latest templates that are compatible with your visual studio and create a project.
Then update the references to the studio 2021 installation folder.
Studio 2021 is a .net framework 4.8 application so you may need to target that but its possible that it will load assemblies from a lower version.

**Comment by luo647** [comment]
using Sdl.FileTypeSupport.*   
using Sdl.Core.* 
using Sdl.* 
failed，cannot find these using;
I have used Visual Studio 2017 and 2019 with trado studio 2021 sdk extension;

**Comment by rwsdwatson** [comment]
Ahh I see.
I think its not going to work as you are trying to load .net 4.8 dependencies in an older framework.

**Comment by luo647** [comment]
Visual Studio 2019 with .NET Framework 4.6.2 
Visual Studio 2019 with .NET Framework 4.8
I tried both combinations, but the problem still exists. Do I need you to give me a new sample project for Trados 2021, or what should I do?

**Comment by githubtestdw** [comment]
I don't have older versions of visual studio installed any more.
If you have Trados 2021 installed and licensed.
and have opened a 2021 sample project in VS 2019 (these target .net4.8)
https://github.com/RWS/trados-studio-api-samples/releases/tag/Studio2021

do they compile for you if not what errors are you getting.

**Comment by luo647** [comment]
> 
![image](https://github.com/RWS/trados-studio-api-samples/assets/132260321/57adc82c-e787-4190-9812-c60b9997a36a)
can you see the image?

**Comment by rwsdwatson** [comment]
You'll need to make sure the .csproj file is picking up the references from the studio 2021 folder (Studio16).

![vsreferences](https://github.com/RWS/trados-studio-api-samples/assets/90462285/7d275a59-0e06-494c-a825-57496fdff31b)

**Comment by rwsdwatson** [comment]
[update the CS proj to Studio16 not studio17](https://github.com/RWS/trados-studio-api-samples/blob/7d5bb9076593d5654fbe56653fd73fc2ad44425d/ProjectAutomation/BatchTaskSamples/PseudoTranslate/Sdl.SDK.BatchTasks.Samples.SimplePseudoTranslate.csproj#L41)
